### ISSUE TITLE
Support running in & out of Rancher Manager cluster

### ISSUE THREAD

**Issue by richardcase** [rancher/turtles#4]
**Story**
As a Rancher Operator,
I want the choice to deploy Rancher Turtles in the same or a different cluster to Rancher Manager,
So that i have choice in my deployment topology.

**Description**
Currently, its assumed thats the operator is running in the same cluster as Rancher Manager. Change the operator so you can optionally supply a reference to a kubeconfig to use (via a secret) instead of using the incluster credentials.

- [ ] #186 
- [x] Change the operator to optionally support using a kubeconfig for creating a client in addition to the in cluster (#19)
- [ ] Define & document RBAC permissions for the kubeconfig (i.e. least privilege)
- [ ] e2e test covering both deployment models

**Comment by salasberryfin** [comment]
As part of rancher-sandbox/rancher-turtles-docs#13, we're doing a collaborative effort to define the workflow for a Rancher operator to be able to use the out of cluster installation topology, including:
- kubeconfig generation.
- least privilege permissions required.
- e2e test scenario.

**Comment by salasberryfin** [comment]
We're pushing for the in-cluster functionality for `Early access - release 1` and will be coming back to this for the next iteration.

**Comment by alexander-demicev** [comment]
Closing this for now, we will reopen the issue later
