### ISSUE TITLE
[EPIC] Review current E2E status

### ISSUE THREAD

**Issue by salasberryfin** [rancher/turtles#815]
# Description

- [x] #824
- [x] #828 - some of them are not running and could be redundant:
  - E2E short: `e2e-short`, `e2e-short-test`
  - E2E long: `e2e-long`, `e2e-long-test`
- [x] #896
- [x] ~~We are using `SPOT` VMs for GCP runners (long tests), can this be a source of failed executions? Investigate if we should be moving to "standard" VMs.~~
- [ ] ~~Runners not picking jobs up: some jobs are not being picked by runners intermittently. Can we identify why this is happening? We've experienced jobs waiting to be picked up and when other jobs are completed, runner would be removed and the waiting job will just time out https://github.com/rancher/turtles/actions/runs/11550471529/attempts/1~~
- [x] https://github.com/rancher/turtles/issues/893
- [x] #898
- [x] #907
